bands: ['z']
grids: ['s_rdesi']
grid_bands: ['z']
abund_grids: ['s_rdesi']
seconds_per_spectrum: 20.
global:
    algor: 1
    f_format: 1
    f_access: 0
    errbar: 1
    covprint: 1
    inter: 3
    cont: -3
    ncont: 500
    ffile: 'frd'
    erfile: 'err'   
    pfile: 'vrd'
    opfile: 'opf$i'
    offile: 'ndl$i'
    sffile: 'nrd$i'
    nthreads: 12
extensions:
   calib: 
       nov: 0
       cont: 0
       nthreads: 1
       pfile: 'opf$i'
       offile: 'mdl$i'
       sffile: ''
s_rdesi:
   param:
       ndim: 4
       nov: 4
       indv:  1 2 3 4
       indi:  1 2 3 4 
       labels:  ['[a/Fe]','[Fe/H]',  'Teff',  'logg']
       llimits: -0.4  -4. 2300. -0.5
       steps:  0.2   0.5  100.  0.5

