bands: ['b','r','z']
grids: ['s_rdesi']
grid_bands: ['brz']
elem:  [  'Fe',     'Ca',     'C',      'Mg'   ]
proxy: ['[Fe/H]', '[a/Fe]', '[Fe/H]', '[a/Fe]' ]
abund_grids: ['s_rdesi']
seconds_per_spectrum: 20.
global:
    algor: 1
    f_format: 1
    f_access: 0
    errbar: 1
    covprint: 1
    inter: 3
    cont: 3
    ncont: 500
    ffile: 'frd'
    erfile: 'err'   
    pfile: 'vrd'
    opfile: 'opf$i'
    offile: 'ndl$i'
    sffile: 'nrd$i'
    nthreads: 12
extensions:
   calib: 
       nov: 0
       cont: 0
       nthreads: 1
       pfile: 'opf$i'
       offile: 'mdl$i'
       sffile: ''
   abund:
       nov: 1
       indv: $proxy
       nthreads: 12
       pfile: 'opf$i'
       opfile: 'oaf.$elem$i'
       offile: 'nal.$elem$i'
       sffile: 'nad.$elem$i'
       filterfile: 'n_rdesi1.$elem.flt'
       covprop: 1
s_rdesi:
   param:
       ndim: 4
       nov: 4
       indv:  1 2 3 4
       indi:  1 2 3 4 
       labels:  ['[a/Fe]','[Fe/H]',  'Teff',  'logg']
       llimits: -0.4  -4. 2300. -0.5
       steps:  0.2   0.5  100.  0.5
       filterfile: 'n_rz.flt'

