bands: ['b', 'r', 'z']
grids: ['m_rdesi10']
seconds_per_spectrum: 10.
global:
    algor: 3
    f_format: 0
    f_access: 0
    errbar: 1
    covprint: 1
    inter: 3
    ffile: 'frd'
    erfile: 'err'   
    nthreads: 8
m_rdesi10:
   param:
       ndim: 4
       nov: 4
       indv:  1  2  3  4
       cont: 3
       ncont: 100
       pfile: 'vrd'
       opfile: 'opf1'
       offile: 'ndl1'
       sffile: 'nrd1'
       labels:  ['[Fe/H]', '[C/Fe]', 'Teff',  'logg']
       llimits: -6. -1. 4750. 1.0
       steps:  0.5   1.0 250. 0.5
   cal: 
       nov: 0
       cont: 0
       nthreads: 1
       pfile: 'opf1'
       offile: 'mdl1'
       sffile: ''
