bands: ['b', 'r', 'z']
grids: ['m_rdesi1', 'm_rdesi2', 'm_rdesi3', 'm_rdesi4', 'm_rdesi5', 'm_rdesi6', 'm_rdesi7', 'm_rdesi8', 'm_rdesi9']
elem:  [ 'Fe',     'Ca',     'C',       'Mg'   ]
proxy: ['[Fe/H]', '[a/Fe]', '[Fe/H]', '[a/Fe]' ]
abund_grids: ['m_rdesi1', 'm_rdesi2']
seconds_per_spectrum: 10.
global:
    algor: 3
    f_format: 1
    f_access: 0
    errbar: 1
    covprint: 1
    inter: 3
    cont: 3
    ncont: 500
    ffile: 'frd'
    erfile: 'err'
    pfile: 'vrd'
    opfile: 'opf$i'
    offile: 'ndl$i'
    sffile: 'nrd$i'
    nthreads: 8
extensions:
   rteff: 
       nov: 1
       indv: $Teff
       inter: 4
       pfile: 'opf$i'
       opfile: 'opt$i'
   calib: 
       nov: 0
       cont: 0
       nthreads: 1
       pfile: 'opf$i'
       offile: 'mdl$i'
       sffile: ''
   abund:
       nov: 1
       indv: $proxy
       nthreads: 1
       pfile: 'opf$i'
       opfile: 'oaf.$elem$i'
       offile: 'nal.$elem$i'
       sffile: 'nad.$elem$i'
       filterfile: '$synth.$elem.flt'
m_rdesi1:
   param:
       ndim: 5
       nov: 5
       indv: 1 2 3 4 5
       labels:  ['[Fe/H]', '[a/Fe]', 'log10micro', 'Teff',  'logg']
       llimits: -5. -1.  -0.301029995663981 3500. 0.0
       steps:  0.25  0.25 0.301029995663981  250. 0.5
m_rdesi2:
   param:
       ndim: 5
       nov: 5
       indv: 1 2 3 4 5
       labels:  ['[Fe/H]', '[a/Fe]', 'log10micro', 'Teff',  'logg']
       llimits:  -5. -1.  -0.301029995663981 5750. 1.0
       steps:   0.25  0.25 0.301029995663981  250. 0.5
m_rdesi3:
   param:
       ndim: 5
       nov: 5
       indv: 1 2 3 4 5
       labels:  ['[Fe/H]', '[a/Fe]', 'log10micro', 'Teff',  'logg']
       llimits: -5.   -1. -0.301029995663981 7000. 2.0
       steps:   0.25 0.25  0.301029995663981  500. 0.5
m_rdesi4:
   param:
       ndim: 5
       nov: 5
       indv: 1 2 3 4 5
       labels:  ['[Fe/H]', '[a/Fe]', 'log10micro', 'Teff',  'logg']
       llimits: -5. -1.  -0.301029995663981 10000. 3.0
       steps:  0.25  0.25 0.301029995663981  1000. 0.5
m_rdesi5:
   param:
       ndim: 5
       nov: 5
       indv: 1 2 3 4 5
       labels: ['[Fe/H]', '[a/Fe]', 'log10micro', 'Teff',  'logg']
       llimits: -5. -1.  -0.301029995663981 20000. 4.0
       steps:  0.25  0.25 0.301029995663981  1000. 0.5
m_rdesi6:
   param:
       ndim: 2
       nov: 2
       indv: 1 2
       labels: ['Teff' ,'logg']
       llimits: 6000.00      7.00000
       steps:    250. 0.25
m_rdesi7:
   param:
       ndim: 2
       nov: 2
       indv: 1 2
       labels: ['Teff', 'logg']
       llimits: 19000.0       7.00000
       steps:    1000. 0.25
m_rdesi8:
   param:
       ndim: 2
       nov: 2
       indv: 1 2
       labels: ['Teff', 'logg']
       llimits: 10000.00       7.00000
       steps: 1000.  0.25
m_rdesi9:
   param:
       ndim: 2
       nov: 2
       indv:  1 2
       labels: [ 'Teff', 'logg']
       llimits:  15000.00       7.00000
       steps: 5000. 0.25

