bands: ['']
grids: ['n_nsc1','n_nsc2','n_nsc3','n_nsc4','n_nsc5','n_dac1','n_dac2','n_db1','n_db2']
seconds_per_spectrum: 1.
global:
    algor: 1
    f_format: 0
    f_access: 0
    errbar: 1
    covprint: 1
    inter: 3
    cont: 1
    ncont: 0
    ffile: 'frd'
    erfile: 'err'   
    pfile: 'vrd'
    opfile: 'opf$i'
    offile: 'ndl$i'
    sffile: 'nrd$i'
    nthreads: 2
extensions:
   calib:
     nov: 0
     cont: 0
     nthreads: 1
     pfile: 'opf$i'
     offile: 'mdl$i'
     sffile: ''
n_nsc1:
   param:
       ndim: 3 
       nov: 3 
       indv: 1 2 3
       labels:  ['[Fe/H]','Teff', 'logg']
       llimits: -5.   3500.0 0.0
       steps:    0.5   500.0 1.0
n_nsc2:
   param:
      ndim: 3
      nov: 3
      indv: 1 2 3
      labels:  ['[Fe/H]','Teff', 'logg']
      llimits: -5.   5500.0 1.0
      steps:    0.5   500.0 1.0
n_nsc3:
   param:
      ndim: 3
      nov: 3
      indv: 1 2 3
      labels:  ['[Fe/H]','Teff', 'logg']
      llimits: -5.   7000.0 2.0
      steps:    0.5  1000.0 1.0
n_nsc4:
   param:
      ndim: 3
      nov: 3
      indv: 1 2 3
      labels:  ['[Fe/H]','Teff', 'logg']
      llimits: -5.  10000.0 3.0
      steps:    0.5  2000.0 1.0
n_nsc5:
   param:
      ndim: 3
      nov: 3
      indv: 1 2 3
      labels:  ['[Fe/H]','Teff', 'logg']
      llimits: -5.  20000.0 4.0
      steps:    0.5  5000.0 1.0
n_dac1:
   param:
      ndim: 2
      nov: 2
      indv: 1 2
      labels: ['Teff','logg']
      llimits: 6000. 7.0
      steps: 500. 0.5
n_dac2:
   param:
      ndim: 2
      nov: 2
      indv: 1 2
      labels: ['Teff','logg']
      llimits: 10000. 7.0
      steps: 5000. 0.5
n_db1:
   param:
      ndim: 2
      nov: 2
      indv: 1 2
      labels: ['Teff','logg']
      llimits: 10000. 7.0
      steps: 1000. 0.25
n_db2:
   param:
      ndim: 2
      nov: 2
      indv: 1 2
      labels: ['Teff','logg']
      llimits: 15000. 7.0
      steps: 5000. 0.25

